### ISSUE TITLE
Define operator's input type

### ISSUE THREAD

**Issue by onesvat** [mistic100/jQuery-QueryBuilder#414] opened 2017-01-03 18:58 UTC
Hello,

I want add custom operator with selectbox to every filter. Options of selectbox will be same in every filter. How can I do that?

{ type: 'join', optgroup: 'custom', nb_inputs: 1, multiple: false, apply_to: ['string', 'integer'] }

----

_mistic100 edit_: define the input type at operator level, ie: filter A is `type: 'text'` unless operator 'customOp' is selected, then the input becomes a selectbox

**Comment by mistic100** [comment] 2017-01-03 19:12
I don't follow you.

Add an new operator with http://querybuilder.js.org/#operators

**Comment by onesvat** [comment] 2017-01-03 19:19
Thank you for fast reply. I did add but it shows only a textbox. I want to add selectbox.

**Comment by mistic100** [comment] 2017-01-03 19:21
could you be more specific ? QueryBuilder is just a bunch of selects and inputs
did you read the doc about filter `type` and `input` http://querybuilder.js.org/#filters

**Comment by onesvat** [comment] 2017-01-03 19:40
In short, I want to allow users to make join queries. In frontend, user can choose join operator with lists of other available columns in additions to standard equal, not equal, less than operators.

If you see the screenshot below, I want that products.categories_id can be selected by a selectbox.

![screenshot from 2017-01-03 22 38 12](https://cloud.githubusercontent.com/assets/2061096/21620452/1037d878-d1fd-11e6-939e-74908ab4cff7.png)

**Comment by mistic100** [comment] 2017-01-03 20:24
then use `input: 'select'` and `values` as **clearly** explained in the doc and the example http://querybuilder.js.org/assets/demo-basic.js

**Comment by onesvat** [comment] 2017-01-03 20:40
I know it however, if i change input to select, all operators will become select-boxes.

Let's I have a string filter, it has contains, not_contains, equal, not equal etc operators with only one input area. I want to add additional custom operator to this, but with one exception it is selected by a selectbox.

Hope, it is understable enough :)

Thank you for your helps.

**Comment by mistic100** [comment] 2017-01-03 20:42
Finally a real description of the need !!

It's not possible, maybe in the future. I don't know when.

**Comment by mistic100** [comment] 2017-01-03 20:47
This is actually a duplicate of #284

**Closed by mistic100** 2017-01-03 20:47 UTC
Labels: feature

**Comment by Sandbird** [comment] 2019-09-29 10:30
Sorry to revive this, but is there any news about this feature ? I've found multiple references to #284 but i cant find any info on actual implementation of this. What's the status ?
Thank you
