### ISSUE TITLE
Query Builder selectize not able to set values if we use ajax.

### ISSUE THREAD

**Issue by surajMetkar33** [mistic100/jQuery-QueryBuilder#587] opened 2017-10-31 13:39 UTC
selectize data is comming from : http://querybuilder.js.org/assets/demo-data.json

Every thing is working as expected like creating the conditions and building the rules from JSON rule
but if i start using selectize with AJAX, building the condition is working fine but not able to reconstruct the condition from rules JSON.

I think that, value setter function has something to do with this, please help.

Working Code : 

```
protected rules_basic = {
        "condition": "AND",
        "rules": [
          {
            "id": "name",
            "field": "name",
            "type": "string",
            "input": "text",
            "operator": "equal",
            "value": "9"
          }
        ],
        "valid": true
      };



    private getNewQueryBuilder() {

        // Fix for Selectize
        $('#builder').on('afterCreateRuleInput.queryBuilder', function(e, rule) {
            if (rule.filter.plugin == 'selectize') {
            rule.$el.find('.rule-value-container').css('min-width', '200px')
                .find('.selectize-control').removeClass('form-control');
            }
        });

        $('#builder').queryBuilder({
            plugins: ['bt-tooltip-errors'],

            filters: [
                {
                    id: 'name',
                    label: 'Selectize',
                    type: 'string',
                    plugin: 'selectize',
                    plugin_config: {
                      valueField: 'id',
                      labelField: 'name',
                      searchField: 'name',
                      sortField: 'name',
                      create: true,
                      maxItems: 1,
                      plugins: ['remove_button'],
                      onInitialize: function() {
                        var that = this;
                
                        if (localStorage.demoData === undefined) {
                          $.getJSON('http://querybuilder.js.org/assets/demo-data.json', function(data) {
                            localStorage.demoData = JSON.stringify(data);
                            data.forEach(function(item) {
                              that.addOption(item);
                            });
                          });
                        }
                        else {
                          JSON.parse(localStorage.demoData).forEach(function(item) {
                            that.addOption(item);
                          });
                        }
                      }
                    },
                    valueSetter: function(rule, value) {
                      rule.$el.find('.rule-value-container input')[0].selectize.setValue(value);
                    }
                }
            ],

            rules: this.rules_basic
        });
```

Code Not working with Ajax : 

```
protected rules_basic = {
        "condition": "AND",
        "rules": [
          {
            "id": "name",
            "field": "name",
            "type": "string",
            "input": "text",
            "operator": "equal",
            "value": "9"
          }
        ],
        "valid": true
      };



    private getNewQueryBuilder() {

        // Fix for Selectize
        $('#builder').on('afterCreateRuleInput.queryBuilder', function(e, rule) {
            if (rule.filter.plugin == 'selectize') {
            rule.$el.find('.rule-value-container').css('min-width', '200px')
                .find('.selectize-control').removeClass('form-control');
            }
        });

        $('#builder').queryBuilder({
            plugins: ['bt-tooltip-errors'],

            filters: [
                {
                    id: 'name',
                    label: 'name',
                    type: 'string',
                    plugin: 'selectize',
                    plugin_config: {
                      valueField: 'id',
                      labelField: 'name',
                      searchField: 'name',
                      sortField: 'name',
                      create: false,
                      //maxItems: 1,
                      options: [],
                      plugins: ['remove_button'],
                      render: {
                        option: function(item, escape) {
                          return '<div>'+item.name+'</div>';
                        }
                      },
                      load: function(query, callback) {
                        var that = this;
                        if (!query.length) return callback();
                        $.ajax({
                          url: 'http://querybuilder.js.org/assets/demo-data.json?query=' + encodeURIComponent(query),
                          type: 'GET',
                          error: function() {
                            callback();
                          },
                          success: function(res) {
                            callback(res);
                          }
                        });
                      }
                    },
                    valueSetter: function(rule, value) {
                      rule.$el.find('.rule-value-container input')[0].selectize.setValue(value);
                    }
                }
            ],

            rules: this.rules_basic
        });
```

**Comment by surajMetkar33** [comment] 2017-10-31 13:41
![empty](https://user-images.githubusercontent.com/33083869/32226698-4b4232ce-be6f-11e7-8a07-ee9cb72eb8cc.png)

**Comment by mistic100** [comment] 2017-10-31 21:47
This is totally normal, the AJAX request is asynchronous and only executed on request so when you call `setValue` on selectize, the plugin doesn't know what to do because it doesn't have any items.

So before calling `setValue` you must call `addOption`
See selectize doc https://github.com/selectize/selectize.js/blob/master/docs/api.md

I am closing this because it has nothing specific to QueryBuilder, you could have a standalone selectize input and reproduce the issue.

**Closed by mistic100** 2017-10-31 21:47 UTC
