### ISSUE TITLE
add custom Operator with two inputs: text and select

### ISSUE THREAD

**Issue by SarahTrees** [mistic100/jQuery-QueryBuilder#481] opened 2017-05-02 10:35 UTC
I need some new operators apply_to: ['string'].
I use the new and the default operators on filters - operators.

I found https://github.com/mistic100/jQuery-QueryBuilder/issues/403 and was able to create operator
"contains_one"
{ type: 'contains_one',  nb_inputs: 1, multiple: false, apply_to: ['string'] },
It works, thank you very much!

Now I need a new operator "contains_near". By these operator I need a standard text input AND a selectbox.

With
{ type: 'contains_near',  nb_inputs: 2, multiple: false, apply_to: ['string'] },
I create two standard text inputs.

Where can I define differend types of inputs?
How can I change the second one to a select?

Thank for your help!

**Comment by mistic100** [comment] 2017-05-02 12:03
Hello

duplicate of #284

**Closed by mistic100** 2017-05-02 12:03 UTC
