### ISSUE TITLE
Textarea input for specific operators

### ISSUE THREAD

**Issue by Bamestra** [mistic100/jQuery-QueryBuilder#488] opened 2017-05-10 13:38 UTC
The documentation tells me I can set input types per filter. Might there also be a way to set input types per operator?

For all my filters the input is set to 'text' to show a normal small input field. When the 'in' and 'not_in' operators are selected though, I would like to show a textarea.

**Comment by mistic100** [comment] 2017-05-10 14:26
Duplicate of #284

**Closed by mistic100** 2017-05-10 14:26 UTC

**Comment by Bamestra** [comment] 2017-05-12 10:27
For my particular need this seems to work okay; All my filters are set to `input: textarea` and I style the textarea according to which operator is selected. For every operator but in/not_in the textarea looks like a normal text input.
```
// After the operator has been updated.
$('#builder').on('afterUpdateRuleOperator.queryBuilder', function(e, rule, error, value) {

  // Select the input textarea. 
  var input = rule.$el.find($.fn.queryBuilder.constructor.selectors.rule_value);

  // Set the class attribute based on which operator is selected.
  if(rule.operator.type === 'in' || rule.operator.type === 'not_in') {
    input.attr('class', 'form-control class1');
  } else {
    input.attr('class', 'form-control class2');
  }

  // Prevent the ENTER key from placing newlines.
  input.keydown(function(e) {
    if (e.keyCode == 13) {
      e.preventDefault();
    }
  });
});
```

```
<style>
  textarea.class1 {
    height: 108px;
    width: 200px;
    resize: none;
  }

  textarea.class2 {
    height: 36px;
    width: 200px;
    resize: none;
  }
</style>
```

**Comment by SarahTrees** [comment] 2017-05-16 11:53
Only  --after-- "afterUpdateRuleOperator". When these rule is default, nothing will happen.
When [in] or [not_in] is the first operator, then the event will not fire.
