### ISSUE TITLE
Column Selection Drop down is not close.

### ISSUE THREAD

**Issue by jackryu** [mistic100/jQuery-QueryBuilder#462] opened 2017-04-11 16:20 UTC
![image](https://cloud.githubusercontent.com/assets/6933841/24919216/90bae83c-1f00-11e7-9a9c-e499fe685b2e.png)

**:::: ERROR :::::**
_if i am click on name drop down and select any field. field is selected but drop down is not close._

**Comment by mistic100** [comment] 2017-04-11 17:10
Hi

I cannot reproduce nor on the website nor on the demo file.

Setup an online an example where I can reproduce it.

**Comment by jackryu** [comment] 2017-04-11 18:09
**i am not understand what is "nor" file ?**  but this is working if  i am removed yellow highlighter line in below image .

![image](https://cloud.githubusercontent.com/assets/6933841/24923661/d93e5c6a-1f0f-11e7-8402-1f06d480d272.png)

**Comment by mistic100** [comment] 2017-04-11 18:16
"nor"... it's an english word http://dictionary.cambridge.org/grammar/british-grammar/questions-and-negative-sentences/neither-neither-nor-and-not-either

If you don't want to publish an example of the problem, I close the issue.

**Comment by jackryu** [comment] 2017-04-12 11:26
Oho - Sorry. Yes please close this issue my issue is resolved

**Closed** 2017-04-12 12:16 UTC
