### ISSUE TITLE
Operator dependent input type

### ISSUE THREAD

**Issue by giero** [mistic100/jQuery-QueryBuilder#518] opened 2017-06-23 10:38 UTC
Hello,

I'm stuck with a problem, maybe someone would have some idea. By default input type is defined for a filter (like 'text', 'number', 'textarea', 'radio', 'checkbox' or 'select').
Is it possible to change input field type according to operator we choose?

Examples:
 - for 'equal' operator -> select with one option possible to select
 - for 'contains' operator -> input text
 - for 'in' operator -> select with multiple options to select or even better - sth like [bootstap collecion](http://bootstrap.mohrenweiserpartner.de/mopa/bootstrap/forms/collections)

Is it possible to achieve this somehow? Thanks for any clue.

**Comment by mistic100** [comment] 2017-06-23 12:24
Hello

duplicate of #251 and #284

**Closed by mistic100** 2017-06-23 12:24 UTC
