### ISSUE TITLE
Multi-level Menu of Filters

### ISSUE THREAD

**Issue by codewithshehraz** [mistic100/jQuery-QueryBuilder#853] opened 2020-01-06 12:24 UTC
Hi, I need to add multi-level filter. As you can see in below mock-up screen there is Demographic filter and I want to have its multiple levels. Can I do this using plugin's or events. When ever the specific value i.e Date or Code selected from sub menu, its input should show accordingly. 
Please guide me. 
![Capture](https://user-images.githubusercontent.com/39002150/71817662-624bdf80-30a8-11ea-98b6-afa46eb3a614.PNG)

Thanks,

**Comment by mistic100** [comment] 2020-01-06 12:36
Duplicate of #653 (and many others).

TLDR : is not currently possible.

**Closed** 2020-01-06 12:36 UTC

**Comment by codewithshehraz** [comment] 2020-01-10 13:35
@mistic100 I am able to create a multi level drop down by changing the template in query builder configuration option. But when I am select any rule from drop down it didn't create rule. Is there any other configuration that I needed. 
templates:{
      filterSelect:`{{ var optgroup = null; }}
          <div class="rule-container dropdown dropdown-inline form-control" name="{{= it.rule.id }}_filter">
            {{? it.settings.display_empty_filter }}
          <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">Select Condition </span></a>
          <ul class="dropdown-menu" role="menu">
            {{?}}
            {{~ it.filters: filter }}
              {{? optgroup !== filter.optgroup }}
                {{? optgroup !== null }}</ul></li>{{?}}
                {{? (optgroup = filter.optgroup) !== null }}
              <li data-original-index="{{=filter.options_index}}" class=""><a class="opt trigger right-caret" ><span class="text">{{= it.translate(it.settings.optgroups[optgroup]) }} </span></a>
              <ul class="dropdown-menu sub-menu">
                {{?}}
              {{?}}
              <li class="opt" data-original-index="{{=filter.options_index}}" value="{{= filter.id }}" ><a class="opt"><span class="text">{{= it.translate(filter.label) }}</span></a></li>
            {{~}}
            {{? optgroup !== null }}</ul></li>{{?}}
          </div>`
    },
filters: [

      /*
       * select
       */
      {
        id: 'all',
        label: 'All of the conditions are met:',
        operator:['equal']
      },
      {
        id: 'age',
        label: 'Age',
        type: 'integer',
        optgroup: 'Demographics',
        options_index:'1',
        operators: ['equal', 'not_equal', 'is_null', 'is_not_null']
      },
      {
        id: 'ageWithEffectiveDate',
        label: 'Age With Effective Date',
        type: 'datetime',
        optgroup: 'Demographics',
        options_index:'2',
        operators: ['equal', 'not_equal', 'is_null', 'is_not_null']
      },
      {
        id: 'ageVariable',
        label: 'Age Variable',
        type: 'string',
        optgroup: 'Demographics',
        options_index:'3',
        operators: ['equal', 'not_equal', 'is_null', 'is_not_null']
      },
      {
        id: 'encounters',
        label: 'Encounters',
        type: 'string',
        optgroup: 'Episode of Care',
        options_index:'4',
        operators: ['equal', 'not_equal', 'is_null', 'is_not_null']
      },
      {
        id: 'procedures',
        label: 'Procedures',
        type: 'string',
        optgroup: 'Episode of Care',
        options_index:'5',
        operators: ['equal', 'not_equal', 'is_null', 'is_not_null']
      },
      {
        id: 'cdVariable',
        label: 'CD Variable',
        type: 'string',
        optgroup: 'Episode of Care',
        options_index:'6',
        operators: ['equal', 'not_equal', 'is_null', 'is_not_null']
      }]
![image](https://user-images.githubusercontent.com/39002150/72150402-4b1e3200-33c7-11ea-9ea9-900eb633e6a8.png)
